# Generated by Django 5.1.4 on 2025-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursy_Online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/pfp.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
