# Generated by Django 5.1.7 on 2025-06-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kursy_Online', '0002_codingexercise_difficulty_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingexercise',
            name='allowed_languages',
        ),
        migrations.RemoveField(
            model_name='codingexercise',
            name='difficulty',
        ),
    ]
